const express = require("express");
const Router = express.Router();
const authController = require("../controller/authController");
const reviewController = require("../controller/reviewController");
Router.post("/addReview", reviewController.addReview);
Router.get("/allReviews", reviewController.getAllReviews);
Router.use(authController.protect);
Router.patch("/updateReview/:id", reviewController.updateReview);
Router.delete("/deleteReview/:id", reviewController.deleteReview);
module.exports = Router;
